/****** Object:  Table [dbo].[DV_ENTITYLINKS]    Script Date: 09/02/2023 11:26:42 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DV_ENTITYLINKS](
	[ID] [int] NOT NULL,
	[TBL] [varchar](128) NOT NULL,
	[PROCESSED] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC,
	[TBL] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[DV_ENTITYLINKS] ADD  DEFAULT ((0)) FOR [PROCESSED]
GO

